#  ***MILESTONE*** **1**

In [1]:
!pip install keras-tuner -q
import keras_tuner
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical, plot_model  
from sklearn.neural_network import MLPClassifier

     |████████████████████████████████| 135 kB 12.2 MB/s 
     |████████████████████████████████| 1.6 MB 67.7 MB/s 


In [2]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [3]:
import glob
from skimage.io import imread
from skimage.color import gray2rgb
import pandas as pd, numpy as np
from sklearn import datasets, preprocessing, linear_model
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

def convert_to_csv(path_to_dataset):
    image_paths = glob.glob(path_to_dataset + '/*/*/*.JPEG')
    
    train_imgs = []
    test_imgs = []

    for image_path in image_paths:
        image = imread(image_path)
        if image.shape[-1] != 3:
            image = gray2rgb(image)
        if image_path.split('/')[-3] == 'train':
            train_imgs.append(image.ravel().tolist() + [image_path.split('/')[-2]])
        else:
            test_imgs.append(image.ravel().tolist() + [image_path.split('/')[-2]])
    
    img_0 = imread(image_paths[0])
    column_names = [f"p_{x}" for x in range(np.prod(img_0.shape))] + ['label']
    
    train_df = pd.DataFrame(train_imgs, columns=column_names)
    test_df = pd.DataFrame(test_imgs, columns=column_names)

    train_df.to_csv(path_to_dataset+'/train.csv', index=False)
    test_df.to_csv(path_to_dataset+'/test.csv', index=False)

In [4]:
# path = '/content/gdrive/MyDrive/Group_5'
# convert_to_csv(path)

In [5]:
train_data = pd.read_csv('/content/gdrive/MyDrive/Group_5/train.csv')
test_data = pd.read_csv('/content/gdrive/MyDrive/Group_5/test.csv')

In [6]:
le = LabelEncoder()
train_data['label'] = le.fit_transform(train_data['label'])
test_data['label'] = le.fit_transform(test_data['label'])

In [7]:
X1 = train_data.iloc[:,0:-1]
y1 = train_data['label']

X2 = test_data.iloc[:,0:-1]
y2 = test_data['label']

print("shape of X1 =", X1.shape)
print("shape of y1 =", y1.shape)

print("shape of X2 =", X2.shape)
print("shape of y2 =", y2.shape)

shape of X1 = (2150, 12288)
shape of y1 = (2150,)
shape of X2 = (250, 12288)
shape of y2 = (250,)


In [8]:
X1_norm = preprocessing.minmax_scale(X1)
X2_norm = preprocessing.minmax_scale(X2)

In [9]:
model = linear_model.LogisticRegression(C = 1, fit_intercept=True, solver='lbfgs', max_iter=100)
model = model.fit(X1_norm, y1)
y_predict = model.predict(X2_norm)

acc_training = np.mean(y1 == model.predict(X1_norm))*100
acc_testing = np.mean(y2 == y_predict)*100
print("Training accuracy (%) =", acc_training)
print("Testing accuracy (%) =", acc_testing)

Training accuracy (%) = 88.23255813953489
Testing accuracy (%) = 32.0


/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [10]:
CNF = confusion_matrix(y2, y_predict)
print(CNF)

[[13  7 15  5 10]
 [ 8 21  6  4 11]
 [17  6 21  3  3]
 [10 13 12  7  8]
 [10 13  6  3 18]]


In [11]:
FP = CNF.sum(axis=0) - np.diag(CNF)
FN = CNF.sum(axis=1) - np.diag(CNF)
TP = np.diag(CNF)
TN = CNF.sum() - FP - FN - TP 

TPR = TP/(TP+FN)
TNR = TN/(TN+FP) 
PPV = TP/(TP+FP)
NPV = TN/(TN+FN)
F1 = 2*((PPV)*(TPR)/(PPV + TPR)) 

for i in range(5):
  dataset_name = ""
  if i == 0:
    dataset_name = "fence"
  elif i == 1:
    dataset_name = "pill-bottle"
  elif i == 2:
    dataset_name = "projectile"
  elif i == 3:
    dataset_name = "reel"
  elif i == 4:
    dataset_name = "snail"

  print("Sensitivity of",dataset_name,":",TPR[i])
  print("Specificity of",dataset_name,":",TNR[i])
  print("PPV of",dataset_name,":",PPV[i])
  print("NPV of",dataset_name,":",NPV[i])
  print("F1 Score of",dataset_name,":",F1[i])
  print("")

Sensitivity of fence : 0.26
Specificity of fence : 0.775
PPV of fence : 0.22413793103448276
NPV of fence : 0.8072916666666666
F1 Score of fence : 0.24074074074074073

Sensitivity of pill-bottle : 0.42
Specificity of pill-bottle : 0.805
PPV of pill-bottle : 0.35
NPV of pill-bottle : 0.8473684210526315
F1 Score of pill-bottle : 0.3818181818181818

Sensitivity of projectile : 0.42
Specificity of projectile : 0.805
PPV of projectile : 0.35
NPV of projectile : 0.8473684210526315
F1 Score of projectile : 0.3818181818181818

Sensitivity of reel : 0.14
Specificity of reel : 0.925
PPV of reel : 0.3181818181818182
NPV of reel : 0.8114035087719298
F1 Score of reel : 0.19444444444444445

Sensitivity of snail : 0.36
Specificity of snail : 0.84
PPV of snail : 0.36
NPV of snail : 0.84
F1 Score of snail : 0.36



In [1]:
# Everything is okay till this point 

# MILESTONE 2 QUESTIONS

# 1. How does neural network extract complex features automatically?

# 2. Train a four layer (one input layer, one output layer, two hidden layers) neural network using keras with some random number of neurons in the hidden layers on your dataset and 
#    use the test dataset to evaluate the model's performance (accuracy, sensitivity, specificity, confusion matrix). Use the logistic activation functions for the hidden layers, and softmax for the output layer. Compare the results
#    with that of the Logistic Regression model you for Milestone 1.

# 3. Train the same model again, but now use one of the technique you mentioned to deal with unbalanced dataset. How does the performance metrics change? Explain

# 4. What are the hyper-parameters for a neural network model? What segment of the dataset is used to find these hyper-parameters (train/test/valid)? 

# 5. If your dataset is missing one of these segments, you need to create one by randomly splitting the train dataset. REMEMBER to set stratify=y in the train_test_split function. What does this parameter do?

# 6. Use the keras-tuner library to find the optimal neural network hyperparameters for this model. Use BayesianOptimization tuner instead of RandomSearch tuner with  max_trials=300. 
#    Train each model for >= 100 epochs // Use the "fixed" dataset generated in step 3//. Use the following search space for the hyper-parameters:
#    1. Number of hidden layers: hp.Int between 2 to 5
#    2. Neurons in each hidden layer: hp.Int between 16 to 128 with a step size of 16
#    3. Activation function of the hidden layers: hp.Choice between relu and sigmoid.

# REMEMBER to use the validation set to tune the hyper-parameters, and the test set to report the final result. DO NOT use the test set to set any hyper parameter. 
# Compare the results with previous ones.

# ***MILESTONE 2***

In [13]:
#Hyperparameter Tuning
# Flatten the inputs
X_train = X1_norm.reshape(X1_norm.shape[0], -1)
X_test = X2_norm.reshape(X2_norm.shape[0], -1)

# Convert the target to one-hot encoding
y_train = to_categorical(y1, num_classes=5) 
y_test = to_categorical(y2, num_classes=5) 


print("shape of X =", X_train.shape)
print("shape of y =", y_train.shape)

shape of X = (2150, 12288)
shape of y = (2150, 5)


In [14]:
#Question 2
model = Sequential()
model.add( Input(shape = (12288,)) )          #input layer
model.add( Dense(500, activation='sigmoid') )   #hidden layer
model.add( Dense(250, activation='sigmoid') )   #hidden layer
model.add( Dense(5, activation='softmax') )   #output layer, activation must be softmax

model.compile(optimizer='sgd',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# plot_model(model, show_shapes=True, show_dtype=True, show_layer_names=True)
# print(y_test.shape)
model.fit(X_train, y_train, epochs=25, verbose=1)

#test accuracy using reference colab file
y_pred = model.predict(X_test)
y_predicted = np.argmax(y_pred, axis=1)
y_actual = np.argmax(y_test, axis=1)
acc_testing = np.mean(y_actual == y_predicted)*100
print("Testing accuracy (%) =", acc_testing)

Epoch 1/25
68/68 [==============================] - 2s 25ms/step - loss: 1.5945 - accuracy: 0.2502
Epoch 2/25
68/68 [==============================] - 2s 25ms/step - loss: 1.5606 - accuracy: 0.2819
Epoch 3/25
68/68 [==============================] - 2s 24ms/step - loss: 1.5450 - accuracy: 0.2912
Epoch 4/25
68/68 [==============================] - 2s 25ms/step - loss: 1.5240 - accuracy: 0.3479
Epoch 5/25
68/68 [==============================] - 2s 24ms/step - loss: 1.5111 - accuracy: 0.3558
Epoch 6/25
68/68 [==============================] - 2s 24ms/step - loss: 1.4950 - accuracy: 0.3605
Epoch 7/25
68/68 [==============================] - 2s 24ms/step - loss: 1.4848 - accuracy: 0.3693
Epoch 8/25
68/68 [==============================] - 2s 23ms/step - loss: 1.4738 - accuracy: 0.3781
Epoch 9/25
68/68 [==============================] - 2s 23ms/step - loss: 1.4605 - accuracy: 0.3833
Epoch 10/25
68/68 [==============================] - 2s 25ms/step - loss: 1.4525 - accuracy: 0.3907
Epoch 11/

In [15]:
#Verify the confusion matrix
CNF = confusion_matrix(y_actual, y_predicted)
print(CNF)

[[20 17 13  0  0]
 [ 8 35  4  1  2]
 [13 11 26  0  0]
 [13 18 14  1  4]
 [18 19  3  0 10]]


In [16]:
FP = CNF.sum(axis=0) - np.diag(CNF)
FN = CNF.sum(axis=1) - np.diag(CNF)
TP = np.diag(CNF)
TN = CNF.sum() - FP - FN - TP 

TPR = TP/(TP+FN)
TNR = TN/(TN+FP) 
PPV = TP/(TP+FP)
NPV = TN/(TN+FN)
F1 = 2*((PPV)*(TPR)/(PPV + TPR)) 

for i in range(5):
  dataset_name = ""
  if i == 0:
    dataset_name = "fence"
  elif i == 1:
    dataset_name = "pill-bottle"
  elif i == 2:
    dataset_name = "projectile"
  elif i == 3:
    dataset_name = "reel"
  elif i == 4:
    dataset_name = "snail"

  print("Sensitivity of",dataset_name,":",TPR[i])
  print("Specificity of",dataset_name,":",TNR[i])
  print("PPV of",dataset_name,":",PPV[i])
  print("NPV of",dataset_name,":",NPV[i])
  print("F1 Score of",dataset_name,":",F1[i])
  print("")

Sensitivity of fence : 0.4
Specificity of fence : 0.74
PPV of fence : 0.2777777777777778
NPV of fence : 0.8314606741573034
F1 Score of fence : 0.3278688524590164

Sensitivity of pill-bottle : 0.7
Specificity of pill-bottle : 0.675
PPV of pill-bottle : 0.35
NPV of pill-bottle : 0.9
F1 Score of pill-bottle : 0.4666666666666667

Sensitivity of projectile : 0.52
Specificity of projectile : 0.83
PPV of projectile : 0.43333333333333335
NPV of projectile : 0.8736842105263158
F1 Score of projectile : 0.4727272727272728

Sensitivity of reel : 0.02
Specificity of reel : 0.995
PPV of reel : 0.5
NPV of reel : 0.8024193548387096
F1 Score of reel : 0.038461538461538464

Sensitivity of snail : 0.2
Specificity of snail : 0.97
PPV of snail : 0.625
NPV of snail : 0.8290598290598291
F1 Score of snail : 0.30303030303030304



In [17]:
# Question-3
# Method for unbalanced datasets using oversampling (SMOTE)
# Try Image Augmentation
from imblearn.over_sampling import SMOTE

smote = SMOTE()

X_train_oversampled, y_train_oversampled = smote.fit_resample(X_train, y_train)

model = Sequential()
model.add( Input(shape = (12288,)) )         #input layer
model.add( Dense(500, activation='sigmoid') ) #hidden layer
model.add( Dense(250, activation='sigmoid') )  #hidden layer
model.add( Dense(5, activation='softmax') )  #output layer, activation must be softmax

model.compile(optimizer='sgd',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# plot_model(model, show_shapes=True, show_dtype=True, show_layer_names=True)
model.fit(X_train_oversampled, y_train_oversampled, epochs=25, verbose=1)

# print(X_train_oversampled.shape)
# print(y_train_oversampled.shape)

#test accuracy using reference colab file
y_pred = model.predict(X_test)
y_predicted = np.argmax(y_pred, axis=1)
y_actual = np.argmax(y_test, axis=1)
acc_testing = np.mean(y_actual == y_predicted)*100
print("Testing accuracy (%) =", acc_testing)

Epoch 1/25
79/79 [==============================] - 2s 27ms/step - loss: 1.6094 - accuracy: 0.2160
Epoch 2/25
79/79 [==============================] - 2s 26ms/step - loss: 1.5836 - accuracy: 0.2632
Epoch 3/25
79/79 [==============================] - 2s 27ms/step - loss: 1.5626 - accuracy: 0.2924
Epoch 4/25
79/79 [==============================] - 3s 36ms/step - loss: 1.5502 - accuracy: 0.3152
Epoch 5/25
79/79 [==============================] - 2s 26ms/step - loss: 1.5368 - accuracy: 0.3304
Epoch 6/25
79/79 [==============================] - 2s 25ms/step - loss: 1.5215 - accuracy: 0.3436
Epoch 7/25
79/79 [==============================] - 2s 26ms/step - loss: 1.5085 - accuracy: 0.3568
Epoch 8/25
79/79 [==============================] - 2s 26ms/step - loss: 1.4945 - accuracy: 0.3760
Epoch 9/25
79/79 [==============================] - 2s 25ms/step - loss: 1.4842 - accuracy: 0.3856
Epoch 10/25
79/79 [==============================] - 2s 24ms/step - loss: 1.4727 - accuracy: 0.3896
Epoch 11/

In [18]:
c = 0
for i in range(len(np.argmax(y_train_oversampled, axis=1))):
  if np.argmax(y_train_oversampled, axis=1)[i] == 4:
    c += 1
print(c)


500


In [19]:
print(X_train_oversampled.shape)
print(y_train_oversampled.shape)
print(X_test.shape)
print(y_test.shape)

(2500, 12288)
(2500, 5)
(250, 12288)
(250, 5)


In [20]:
#Verify the confusion matrix
CNF = confusion_matrix(y_actual, y_predicted)
print(CNF)

[[ 6  2  8  0 34]
 [ 2  6  1  0 41]
 [ 0  2 17  1 30]
 [ 1  0  6  0 43]
 [ 4  0  0  0 46]]


In [21]:
#fence output of performance metrics
FP = CNF.sum(axis=0) - np.diag(CNF)
FN = CNF.sum(axis=1) - np.diag(CNF)
TP = np.diag(CNF)
TN = CNF.sum() - FP - FN - TP 

TPR = TP/(TP+FN)
TNR = TN/(TN+FP) 
PPV = TP/(TP+FP)
NPV = TN/(TN+FN)
F1 = 2*((PPV)*(TPR)/(PPV + TPR)) 

for i in range(5):
  dataset_name = ""
  if i == 0:
    dataset_name = "fence"
  elif i == 1:
    dataset_name = "pill-bottle"
  elif i == 2:
    dataset_name = "projectile"
  elif i == 3:
    dataset_name = "reel"
  elif i == 4:
    dataset_name = "snail"

  print("Sensitivity of",dataset_name,":",TPR[i])
  print("Specificity of",dataset_name,":",TNR[i])
  print("PPV of",dataset_name,":",PPV[i])
  print("NPV of",dataset_name,":",NPV[i])
  print("F1 Score of",dataset_name,":",F1[i])
  print("")

Sensitivity of fence : 0.12
Specificity of fence : 0.965
PPV of fence : 0.46153846153846156
NPV of fence : 0.8143459915611815
F1 Score of fence : 0.19047619047619047

Sensitivity of pill-bottle : 0.12
Specificity of pill-bottle : 0.98
PPV of pill-bottle : 0.6
NPV of pill-bottle : 0.8166666666666667
F1 Score of pill-bottle : 0.19999999999999998

Sensitivity of projectile : 0.34
Specificity of projectile : 0.925
PPV of projectile : 0.53125
NPV of projectile : 0.8486238532110092
F1 Score of projectile : 0.4146341463414634

Sensitivity of reel : 0.0
Specificity of reel : 0.995
PPV of reel : 0.0
NPV of reel : 0.7991967871485943
F1 Score of reel : nan

Sensitivity of snail : 0.92
Specificity of snail : 0.26
PPV of snail : 0.23711340206185566
NPV of snail : 0.9285714285714286
F1 Score of snail : 0.3770491803278689



<ipython-input-21-cffe17b5b6b2>:11: RuntimeWarning: invalid value encountered in true_divide
  F1 = 2*((PPV)*(TPR)/(PPV + TPR))


In [22]:
#Question 5
X_train1, X_val, y_train1, y_val = train_test_split(X_train_oversampled, y_train_oversampled, stratify = y_train_oversampled ,test_size=0.20, random_state=100)
#what does this parameter do? (stratify = y)

In [23]:
#hyperparameter tuning
# Flatten the inputs
X_train1 = X_train1.reshape(X_train1.shape[0], -1)
X_val = X_val.reshape(X_val.shape[0], -1)

# Conversion to one-hot encoding is not needed 
# Shape of y_train is already (2500,5)

# number_of_classes = 5
# y_train1 = to_categorical(y_train1, num_classes = number_of_classes) 
# y_val = to_categorical(y_val, num_classes = number_of_classes) 

print("shape of X =", X_train1.shape)
print("shape of y =", y_train1.shape)

shape of X = (2000, 12288)
shape of y = (2000, 5)


In [24]:
def build_model(hp):
    model = Sequential()
    model.add( Input(shape = (12288,)) )
    number_of_layers = hp.Int("num_layers", 2, 5)
    for i in range(number_of_layers):
      units = hp.Int(f"units_{i}", min_value=16, max_value=128, step=16)
      activation = hp.Choice("activation", ["relu", "sigmoid"])  
      model.add( Dense(units, activation=activation) ) #hidden layer
    
    model.add( Dense(5, activation='softmax') ) #output layer, activation must be softmax
   
    model.compile(
        optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"],
    )
    return model

In [25]:
model = build_model(keras_tuner.HyperParameters())

In [26]:
from keras_tuner import BayesianOptimization

tuner = keras_tuner.BayesianOptimization(
    hypermodel=build_model,
    objective='val_accuracy',
    max_trials=4,
    num_initial_points=2,
    alpha=0.0001,
    beta=2.6,
    seed=None,
    hyperparameters=None,
    tune_new_entries=True,
    allow_new_entries=True,
    
)

In [27]:
tuner.search(X_train_oversampled, y_train_oversampled, epochs=100, validation_data=(X_val, y_val))
best_model = tuner.get_best_models()[0]

Trial 4 Complete [00h 01m 23s]
val_accuracy: 0.38199999928474426

Best val_accuracy So Far: 0.9980000257492065
Total elapsed time: 00h 07m 19s


In [28]:
tuner.results_summary()


Results summary
Results in ./untitled_project
Showing 10 best trials
Trial summary
Hyperparameters:
num_layers: 2
units_0: 112
activation: relu
units_1: 112
units_2: 32
units_3: 32
units_4: 32
Score: 0.9980000257492065
Trial summary
Hyperparameters:
num_layers: 2
units_0: 128
activation: relu
units_1: 128
units_2: 112
units_3: 112
units_4: 112
Score: 0.9919999837875366
Trial summary
Hyperparameters:
num_layers: 5
units_0: 96
activation: relu
units_1: 48
units_2: 16
units_3: 16
units_4: 16
Score: 0.8700000047683716
Trial summary
Hyperparameters:
num_layers: 2
units_0: 16
activation: sigmoid
units_1: 128
units_2: 16
units_3: 128
units_4: 128
Score: 0.38199999928474426


In [29]:
#why is it 20% 
model.fit(X_train1, y_train1, epochs=100, verbose=1)

#test accuracy using reference colab file
y_pred = model.predict(X_test)
y_predicted = np.argmax(y_pred, axis=1)
y_actual = np.argmax(y_test, axis=1)
acc_testing = np.mean(y_actual == y_predicted)*100
print("Testing accuracy (%) =", acc_testing)

Epoch 1/100
63/63 [==============================] - 1s 5ms/step - loss: 1.7217 - accuracy: 0.1975
Epoch 2/100
63/63 [==============================] - 0s 6ms/step - loss: 1.6096 - accuracy: 0.1825
Epoch 3/100
63/63 [==============================] - 0s 5ms/step - loss: 1.6171 - accuracy: 0.1885
Epoch 4/100
63/63 [==============================] - 0s 5ms/step - loss: 1.6095 - accuracy: 0.1925
Epoch 5/100
63/63 [==============================] - 0s 5ms/step - loss: 1.6095 - accuracy: 0.1895
Epoch 6/100
63/63 [==============================] - 0s 5ms/step - loss: 1.6095 - accuracy: 0.2000
Epoch 7/100
63/63 [==============================] - 0s 6ms/step - loss: 1.6095 - accuracy: 0.2000
Epoch 8/100
63/63 [==============================] - 0s 6ms/step - loss: 1.6094 - accuracy: 0.2000
Epoch 9/100
63/63 [==============================] - 0s 5ms/step - loss: 1.6094 - accuracy: 0.1830
Epoch 10/100
63/63 [==============================] - 0s 6ms/step - loss: 1.6094 - accuracy: 0.1930
Epoch 11/

In [30]:
CNF = confusion_matrix(y_actual, y_predicted)
print(CNF)

[[ 7 12  0 23  8]
 [ 9 24  1 13  3]
 [ 7  0  0 40  3]
 [ 6 11  1 29  3]
 [11 14  0 17  8]]


In [31]:
FP = CNF.sum(axis=0) - np.diag(CNF)
FN = CNF.sum(axis=1) - np.diag(CNF)
TP = np.diag(CNF)
TN = CNF.sum() - FP - FN - TP 

TPR = TP/(TP+FN)
TNR = TN/(TN+FP) 
PPV = TP/(TP+FP)
NPV = TN/(TN+FN)
F1 = 2*((PPV)*(TPR)/(PPV + TPR)) 

for i in range(5):
  dataset_name = ""
  if i == 0:
    dataset_name = "fence"
  elif i == 1:
    dataset_name = "pill-bottle"
  elif i == 2:
    dataset_name = "projectile"
  elif i == 3:
    dataset_name = "reel"
  elif i == 4:
    dataset_name = "snail"

  print("Sensitivity of",dataset_name,":",TPR[i])
  print("Specificity of",dataset_name,":",TNR[i])
  print("PPV of",dataset_name,":",PPV[i])
  print("NPV of",dataset_name,":",NPV[i])
  print("F1 Score of",dataset_name,":",F1[i])
  print("")

Sensitivity of fence : 0.14
Specificity of fence : 0.835
PPV of fence : 0.175
NPV of fence : 0.7952380952380952
F1 Score of fence : 0.15555555555555556

Sensitivity of pill-bottle : 0.48
Specificity of pill-bottle : 0.815
PPV of pill-bottle : 0.39344262295081966
NPV of pill-bottle : 0.8624338624338624
F1 Score of pill-bottle : 0.43243243243243246

Sensitivity of projectile : 0.0
Specificity of projectile : 0.99
PPV of projectile : 0.0
NPV of projectile : 0.7983870967741935
F1 Score of projectile : nan

Sensitivity of reel : 0.58
Specificity of reel : 0.535
PPV of reel : 0.23770491803278687
NPV of reel : 0.8359375
F1 Score of reel : 0.33720930232558133

Sensitivity of snail : 0.16
Specificity of snail : 0.915
PPV of snail : 0.32
NPV of snail : 0.8133333333333334
F1 Score of snail : 0.21333333333333335



<ipython-input-31-e9f6f16e1da6>:10: RuntimeWarning: invalid value encountered in true_divide
  F1 = 2*((PPV)*(TPR)/(PPV + TPR))
